- .gitignore
> Added: .gitignore

- build.sbt
- project/ProjectInfo.scala
- project/build.properties
- project/plugins.sbt
> Added: Project config files

- project/build.properties
Upgraded: sbt 1.3.10 => 1.3.12
> Upgraded: sbt 1.3.10 => 1.3.12

- build.sbt
Upgraded: Effectie and logger-f
> Upgraded: Effectie and logger-f

- build.sbt
Changed: sbt version in `build.sbt` - `1.3.10` => `1.3.12`
> Changed: sbt version in build.sbt - 1.3.10 => 1.3.12

- build.sbt
Added: `sbt-devoops` config for release
> Added: sbt-devoops config for release

- src/main/scala/loggerf/sbt/SbtLogger.scala
Added: `SbtLogger` for logging with `logger-f`
> Added: SbtLogger for logging with logger-f

- src/main/scala/filef/FileError2.scala
- src/main/scala/filef/FileF2.scala
> Added: File util

- src/main/scala/just/sysprocess/SysProcess.scala
Added: `SysProcess` to handle sys process
> Added: SysProcess to handle sys process

- src/main/scala/just/docusaurus/npm/Npm.scala
- src/main/scala/just/docusaurus/npm/NpmCmd.scala
- src/main/scala/just/docusaurus/npm/NpmError.scala
Added: `Npm` util to run npm commands
> Added: Npm util to run npm commands

- src/main/scala/just/docusaurus/JustDocusaurusKeys.scala
Added: `SettingKey`s for `JustDocusaurus`
> Added: SettingKeys for JustDocusaurus

- README.md
- build.sbt
- src/main/scala/docusaur/JustDocusaurusKeys.scala
- src/main/scala/docusaur/npm/Npm.scala
- src/main/scala/docusaur/npm/NpmCmd.scala
- src/main/scala/docusaur/npm/NpmError.scala
- src/main/scala/loggerf/sbt/SbtLogger2.scala
Changed: The project name from `sbt-just-docusaurus` to `sbt-docusaur`
> Changed: The project name from sbt-just-docusaurus to sbt-docusaur

- .github/workflows/build.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
Added: GitHub Actions config and build script files
> Added: GitHub Actions config and build script files

- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
Added: `DocusaurPlugin` with actual plugin features
> Added: DocusaurPlugin with actual plugin features

- build.sbt
- src/main/scala/docusaur/DocusaurPlugin.scala
Added: `GitHubPagesPlugin` as Docusaur's required dependency for publishing Docusaurus website to GitHub Pages
> Added: GitHubPagesPlugin as Docusaur's required dependency

- README.md
- changelogs/0.1.0.md
* `DocusaurPlugin` to install, build and [publish GitHub Pages (using `sbt-github-pages`)](https://kevin-lee.github.io/sbt-github-pages/)
* [All PRs](https://github.com/Kevin-Lee/sbt-docusaur/issues?utf8=%E2%9C%93&q=is%3Aclosed+milestone%3Amilestone1)
> sbt-docusaur v0.1.0

- website/docs/config.md
- website/docs/getting-started.md
Updated: docs - `Essential settings` in `config.md`
> Updated: docs - Essential settings in config.md

- src/main/scala/docusaur/DocusaurKeys.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
Task #21 - Change `docusaurAlgoliaConfigFileName` to `docusaurAlgoliaConfigFilename`
> Task #21 - Change docusaurAlgoliaConfigFileName to docusaurAlgoliaConfigFilename

- website/docs/getting-started.md
> Updated: new version info

- build.sbt
Close #26 - Upgrade `sbt-github-pages`
> Close #26 - Upgrade sbt-github-pages

- project/plugins.sbt
- website/docs/getting-started.md
Updated: docs - new version info
Upgraded: sbt-plugin - `sbt-docusaur` itself from `0.1.1` => `0.1.2`
> Updated: docs - new version info

- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
Close #36 - Failed task should throw an exception
> Close #36 - Failed task should throw an exception

- changelogs/0.1.3.md
- project/ProjectInfo.scala
* A failed task should fail properly (#36)
* Use [just-sysprocess](https://github.com/Kevin-Lee/just-sysprocess) (#32)
* Use `logger-f-sbt-logging` from [logger-f](https://logger-f.kevinly.dev/) (#33)
> sbt-docusaur v0.1.3

- project/plugins.sbt
- website/docs/getting-started.md
Updated: v0.1.3 info
Now it uses sbt-docusaur 0.1.3 to publish docs
> Updated: v0.1.3 info

- build.sbt
Close #41 - Upgrade `sbt-github-pages`
> Close #41 - Upgrade sbt-github-pages

- .github/workflows/build.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
- build.sbt
Upgraded: Scala 2.12.11 => 2.12.12
> Upgraded: Scala 2.12.11 => 2.12.12

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
- build.sbt
- project/build.properties
Upgraded: sbt 1.3.12 => 1.3.13
> Upgraded: sbt 1.3.12 => 1.3.13

- changelogs/0.1.4.md
- project/ProjectInfo.scala
* Upgrade [sbt-github-pages](https://kevin-lee.github.io/sbt-github-pages) (#41)
> sbt-docusaur v0.1.4

- project/plugins.sbt
- website/docs/getting-started.md
* Updated: docs
* Upgraded: sbt-docusaur 0.1.3 => 0.1.4
> Updated: docs

- project/plugins.sbt
Upgraded: `sbt-wartremover` 2.4.8 => 2.4.10
> Upgraded: sbt-wartremover 2.4.8 => 2.4.10

- src/main/scala/docusaur/DocusaurPlugin.scala
> Formatting

- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurKeys.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
Close #50 - Add Google Analytics support
> Close #50 - Add Google Analytics support

- build.sbt
- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
- src/main/scala/docusaur/npm/Npm.scala
- src/main/scala/filef/FileF2.scala
* Upgraded: libraries and sbt plugins
* Hedgehog `bd4e0cc785915e0af20d2a7ead5267d49b1de7b1` => `0.5.1`
* github4s `0.24.0` => `0.25.0`
* http4s `0.21.3` => `0.21.6`
* effectie `1.0.0` => `1.3.0`
* logger-f `0.4.0` => `1.3.1`
> Upgraded: libraries and sbt plugins

- .github/workflows/publish-github-pages.yml
- project/plugins.sbt
- website/docusaurus.config.js
Upgraded: `sbt-docusaur` `0.1.4` => `0.2.0`
> Upgraded: sbt-docusaur 0.1.4 => 0.2.0

- .github/workflows/publish-github-pages.yml
- project/plugins.sbt
Upgraded: sbt-docusaur 0.2.0 => 0.2.1
> Upgraded: sbt-docusaur 0.2.0 => 0.2.1

- website/docs/config.md
- website/docs/examples.md
- website/docs/getting-started.md
- website/docs/run.md
Updated: docs with new version info (v0.2.1)
> Updated: docs with new version info (v0.2.1)

- website/docs/config.md
Updated: docs with a few examples
> Updated: docs with a few examples

- build.sbt
Close #65 - Upgrade `sbt-github-pages` to 0.3.0
> Close #65 - Upgrade sbt-github-pages to 0.3.0

- changelogs/0.3.0.md
- project/ProjectInfo.scala
* Upgrade [`sbt-github-pages`](https://github.com/Kevin-Lee/sbt-github-pages) to `0.3.0` (#65)
> sbt-docusaur v0.3.0

- website/docs/getting-started.md
- website/package-lock.json
- website/package.json
> Upgraded: Docusaurus

- build.sbt
Added: `pluginCrossBuild / sbtVersion`
> Added: pluginCrossBuild / sbtVersion

- .github/workflows/build.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/release.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/filef/FileF2.scala
Close #71 - Upgrade libraries and sbt
* sbt-devoops `1.0.3` => `2.0.0` - Changed: GitHub Actions config accordingly
* Cats `2.2.0` => `2.4.2`
* Cats Effect `2.2.0` => `2.3.3`
* github4s `0.25.0` => `0.28.2`
* http4s `0.21.6` => `0.21.19`
> Close #71 - Upgrade libraries and sbt

- .github/workflows/manual-publish-github-pages.yml
- project/plugins.sbt
- website/docs/examples.md
- website/docs/getting-started.md
Changed: publishing GitHub pages is now manual
> Changed: publishing GitHub pages is now manual

- .scalafmt.conf
- build.sbt
- project/build.properties
- project/plugins.sbt
Updated: Config / Upgraded: sbt, libraries and plugin / Added: .scalafmt.conf
> Updated: Config / Upgraded: sbt, libraries and plugin / Added: .scalafmt.conf

- .github/workflows/build.yml
- .github/workflows/manual-publish-github-pages.yml
- .github/workflows/release.yml
Updated: GitHub Actions config files - updated actions
> Updated: GitHub Actions config files - updated actions

- build.sbt
Updated: project config and compiler plugin
> Updated: project config and compiler plugin

- .github/workflows/release.yml
- build.sbt
- project/ProjectInfo.scala
- project/plugins.sbt
Close #80 - Publish directly to Maven Central
> Close #80 - Publish directly to Maven Central

- website/docs/examples.md
- website/docs/getting-started.md
- website/docs/run.md
- website/package-lock.json
Updated: docs - with new version info + new example
> Updated: docs - with new version info + new example

- README.md
- website/docs/getting-started.md
Updated: docs - with new badges
> Updated: docs - with new badges

- website/docs/examples.md
- website/docs/getting-started.md
Updated: docs - with the new version info
> Updated: docs - with the new version info

- website/docs/config.md
Updated: docs - optional config keys
> Updated: docs - optional config keys

- src/main/scala/docusaur/DocusaurKeys.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
- src/main/scala/docusaur/npm/NpmCmd.scala
Close #93 - Add task to run `npm audit fix`
> Close #93 - Add task to run npm audit fix

- build.sbt
Close #96 - Upgrade `sbt-github-pages` to `0.7.0`
> Close #96 - Upgrade sbt-github-pages to 0.7.0

- build.sbt
- project/plugins.sbt
- src/main/scala/filef/FileF2.scala
Upgraded: sbt plugins
- `sbt-devoops` `2.3.0` => `2.10.0`
- `sbt-docusaur` `0.5.0` => `0.6.0`
> Upgraded: sbt plugins

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- website/docs/examples.md
- website/docs/getting-started.md
Updated: The docs with the new version info
> Updated: The docs with the new version info

- build.sbt
Close #103 - Upgrade sbt-github-pages to `0.8.0`
> Close #103 - Upgrade sbt-github-pages to 0.8.0

- build.sbt
- src/main/scala/docusaur/npm/Npm.scala
Close #105 - Upgrade `just-sysprocess` to `1.0.0`
> Close #105 - Upgrade just-sysprocess to 1.0.0

- .scalafmt.conf
- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurKeys.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
- src/main/scala/docusaur/npm/NpmError.scala
Updated: .scalafmt.conf - `2.7.5` => `3.0.0`
> Updated: .scalafmt.conf - 2.7.5 => 3.0.0

- website/docs/examples.md
- website/docs/getting-started.md
Updated: docs - with the new version (0.8.0) info
> Updated: docs - with the new version (0.8.0) info

- build.sbt
Close #110 - Upgrade `sbt-github-pages` to `0.8.1`
> Close #110 - Upgrade sbt-github-pages to 0.8.1

- project/plugins.sbt
- website/docs/examples.md
- website/docs/getting-started.md
* Updated: The docs with new version info
* Upgraded: sbt plugins
> Updated the docs with new version info and upgraded sbt plugins

- project/build.properties
Upgrade: sbt `1.5.1` => `1.5.8`
> Upgrade: sbt 1.5.1 => 1.5.8

- .scalafmt.conf
- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
- src/main/scala/docusaur/npm/NpmCmd.scala
- src/main/scala/errors/StackTraceToString.scala
- src/main/scala/filef/FileError2.scala
- src/main/scala/filef/FileF2.scala
Update: `.scalafmt.conf` and reformat
> Update: .scalafmt.conf and reformat

- build.sbt
Close #120 - Publish to `s01.oss.sonatype.org` (the new Maven central)
> Close #120 - Publish to s01.oss.sonatype.org (the new Maven central)

- .scalafmt.conf
Fix: `.scalafmt.conf` - runner.dialect from `scala3` to `scala212`
> Fix: .scalafmt.conf - runner.dialect from scala3 to scala212

- project/plugins.sbt
Issue #120 - Upgrade `sbt-ci-release` from `1.5.7` to `1.5.10`
> Issue #120 - Upgrade sbt-ci-release from 1.5.7 to 1.5.10

- project/plugins.sbt
Upgrade: sbt-devoops 2.14.0 => 2.15.0
> Upgrade: sbt-devoops 2.14.0 => 2.15.0

- project/build.properties
> Upgrade: sbt 1.6.0 => 1.6.2

- .scalafmt.conf
- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurKeys.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
Close #141 - `Add ALGOLIA_APP_ID` for Algolia
> Close #141 - Add `ALGOLIA_APP_ID` for Algolia

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- project/plugins.sbt
- website/docusaurus.config.js
Upgrade: sbt-docusaur `0.8.1` => `0.9.0`
> Upgrade: sbt-docusaur 0.8.1 => 0.9.0

- website/package-lock.json
- website/package.json
Upgrade: Docusaurus `2.0.0-alpha.74` => `2.0.0-beta.17`
> Upgrade: Docusaurus 2.0.0-alpha.74 => 2.0.0-beta.17

- website/docs/config.md
- website/docs/examples.md
- website/docs/getting-started.md
Update: docs with `v0.9.0` info
> Update: docs with v0.9.0 info

- website/docusaurus.config.js
Update: docs - fix `url` in config `http` => `https`
> Update: docs - fix url in config http => https

- build.sbt
Close #154 - Upgrade `sbt-github-pages` to `0.10.0`
> Close #154 - Upgrade sbt-github-pages to 0.10.0

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- website/package-lock.json
- website/package.json
Update: `package.json` - Docusaurus `2.0.0-beta.14` => `2.0.0-beta.21`
> Update: package.json - Docusaurus 2.0.0-beta.14 => 2.0.0-beta.21

- website/docs/examples.md
- website/docs/getting-started.md
Update: docs with the latest sbt-docusaur version 0.9.0 => 0.11.0
> Update: docs with the latest sbt-docusaur version 0.9.0 => 0.11.0

- website/package-lock.json
- website/package.json
Upgrade: Docusaurus `2.0.0-beta.21` => `2.0.1`
> Upgrade: Docusaurus 2.0.0-beta.21 => 2.0.1

- project/plugins.sbt
Upgrade: sbt-docusaur `0.11.0` => `0.12.0`
> Upgrade: sbt-docusaur 0.11.0 => 0.12.0

- website/docs/examples.md
- website/docs/getting-started.md
Update: docs with the latest sbt-docusaur version info
> Update: docs with the latest sbt-docusaur version info

- build.sbt
`build.sbt` - camelCase to PascalCase in version names
> build.sbt - camelCase to PascalCase in version names

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
Update: GitHub Actions config for the doc site build
> Update: GitHub Actions config for the doc site build

- website/package-lock.json
- website/package.json
Upgrade: Docusaurus 2.0.1 => 2.2.0
> Upgrade: Docusaurus 2.0.1 => 2.2.0

- .scalafmt.conf
- build.sbt
- src/main/scala/docusaur/Docusaur.scala
- src/main/scala/docusaur/DocusaurKeys.scala
- src/main/scala/docusaur/DocusaurPlugin.scala
- src/test/resources/logback.xml
- src/test/scala/docusaur/DocusaurSpec.scala
Close #186 - Support multiple Google Analytics trackingIDs (multiple `GA_TRACKING_ID`s)
> Close #186 - Support multiple Google Analytics trackingIDs (multiple `GA_TRACKING_ID`s)

- website/docs/config.md
- website/docs/examples.md
- website/docs/getting-started.md
Update docs - with the latest version info and updated config:`docusaurGoogleAnalyticsTrackingId` from `Option[String]` to `List[String]`
> Update docs - with the latest version info and updated config:`docusaurGoogleAnalyticsTrackingId` from `Option[String]` to `List[String]`

- project/plugins.sbt
> Bump sbt-docusaur to `0.15.0`

- website/docs/examples.md
- website/docs/getting-started.md
Update: docs - with the latest version info
> Update: docs - with the latest version info

- README.md
Update: README.md with the logo image
> Update: README.md with the logo image

- project/plugins.sbt
- website/docs/examples.md
- website/docs/getting-started.md
Update docs and bump sbt-docusaur
* Update docs: the new version info
* Bump sbt-docusaur to 0.16.0
* Bump sbt-devoops to 3.1.0
> Update docs and bump sbt-docusaur

- website/docusaurus.config.ts
- website/package.json
> Bump Docusaurus to `3.5.2`

- .github/workflows/build.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/release.yml
Update GitHub Actions: Bump setup-java action to v4.7.0, replace SBT caching method, and set actions/cache to v4
> Update GitHub Actions: Bump setup-java action to v4.7.0, replace SBT caching method, and set actions/cache to v4

- project/plugins.sbt
> Bump sbt-docusaur to v0.17.0
