changelogs/0.1.1.md
project/ProjectInfo.scala

* Changed: Setting Key `docusaurAlgoliaConfigFileName` to `docusaurAlgoliaConfigFilename` (#21)

sbt-docusaur v0.1.1

---

changelogs/0.1.2.md
project/ProjectInfo.scala

* Upgrade `sbt-github-pages` to 0.1.2 (#26)

sbt-docusaur v0.1.2

---

build.sbt

* It's done by upgrading sbt-github-pages from 0.1.3 to 0.2.0

Close #31 - Support GitHub Enterprise

---

changelogs/0.2.0.md
project/ProjectInfo.scala

* Support GitHub Enterprise (#31)
* It's done by upgrading `sbt-github-pages` from `0.1.3` to `0.2.0`.
* Add Google Analytics support (#50)
```scala
// The name of Google Analytics config file 
// (default: sys.env.getOrElse("GA_CONFIG_FILENAME", "google-analytics.config.json") )
docusaurGoogleAnalyticsConfigFilename: SettingKey[String]
// Google Analytics Tracking ID. If None, Google Analytics config with an empty object is created.
// (default: sys.env.get("GA_TRACKING_ID") )
docusaurGoogleAnalyticsTrackingId: SettingKey[Option[String]]
// Google Analytics option to anonymize IP.
// If None, the Google Analytics config will not have the `anonymizeIP` field. 
// (default: sys.env.get("GA_ANONYMIZE_IP") )
docusaurGoogleAnalyticsAnonymizeIp: SettingKey[Option[Boolean]]
// Generate the …
```

sbt-docusaur v0.2.0

---

src/main/scala/docusaur/DocusaurPlugin.scala

Fix #58 - Doc site build fails when a Google Analytics config property has an empty String values

Fix #58 - Doc site build fails when a Google Analytics config property has an empty String values

---

changelogs/0.2.1.md
project/ProjectInfo.scala

* Doc site build fails when a Google Analytics config property has an empty String values (#58)

sbt-docusaur v0.2.1

---

changelogs/0.4.0.md
project/ProjectInfo.scala

* Upgrade libraries and sbt (#71)
* `sbt-github-pages`: `0.3.0` => `0.4.0`
* `sbt-devoops`: `1.0.3` => `2.0.0` - Changed: GitHub Actions config accordingly
* `cats`: `2.2.0` => `2.4.2`
* `cats-effect`: `2.2.0` => `2.3.3`
* `github4s`: `0.25.0` => `0.28.2`
* `http4s`: `0.21.6` => `0.21.19`

sbt-docusaur v0.4.0

---

.github/workflows/build.yml
.github/workflows/sbt-build-simple.sh
build.sbt
project/ProjectInfo.scala
project/build.properties
project/plugins.sbt

Close #78 - Upgrade sbt plugin and libraries
* sbt `1.4.9` => `1.5.1`
* sbt-devoops `2.1.0` => `2.3.0`
* sbt-github-pages `0.4.0` => `0.5.0`
* http4s `0.21.20` => `0.21.22`
* cats-core `2.4.2` => `2.6.0`
* cats-effect `2.3.3` => `2.5.0`
* github4s `0.28.2` => `0.28.4`
* effectie `1.9.0` => `1.10.0`
* logger-f `1.9.0` => `1.10.0`

Close #78 - Upgrade sbt plugin and libraries

---

changelogs/0.5.0.md

* Upgrade sbt plugin and libraries (#78)
* sbt `1.4.9` => `1.5.1`
* sbt-devoops `2.1.0` => `2.3.0`
* sbt-github-pages `0.4.0` => `0.5.0`
* http4s `0.21.20` => `0.21.22`
* cats-core `2.4.2` => `2.6.0`
* cats-effect `2.3.3` => `2.5.0`
* github4s `0.28.2` => `0.28.4`
* effectie `1.9.0` => `1.10.0`
* logger-f `1.9.0` => `1.10.0`
* Publish directly to Maven Central (#80)

sbt-docusaur v0.5.0

---

build.sbt
project/plugins.sbt
website/docs/config.md
website/docs/examples.md
website/docs/getting-started.md

Close #87 - Upgrade `sbt-github-pages` to simplify `gitHubPagesOrgName` and `gitHubPagesRepoName` settings

Close #87 - Upgrade sbt-github-pages to simplify gitHubPagesOrgName and gitHubPagesRepoName settings

---

changelogs/0.6.0.md

* Upgrade `sbt-github-pages` to simplify `gitHubPagesOrgName` and `gitHubPagesRepoName` settings (#87)

sbt-docusaur v0.6.0

---

build.sbt
src/main/scala/docusaur/Docusaur.scala
src/main/scala/docusaur/npm/Npm.scala
src/main/scala/filef/FileF2.scala

Close #92 - Upgrade libraries
- cats `2.6.0` => `2.6.1`
- cats-effect `2.5.0` => `2.5.3`
- http4s `0.21.22` => `0.21.27`
- github4s `0.28.4` => `0.28.5`
- effectie `1.10.0` => `1.15.0`
- logger-f `1.10.0` => `1.15.0`
- just-sysprocess `0.6.0` => `0.8.0`

Close #92 - Upgrade libraries

---

changelogs/0.7.0.md

* Upgrade libraries (#92)
* `cats` `2.6.0` => `2.6.1`
* `cats-effect` `2.5.0` => `2.5.3`
* `http4s` `0.21.22` => `0.21.27`
* `github4s` `0.28.4` => `0.28.5`
* `effectie` `1.10.0` => `1.15.0`
* `logger-f` `1.10.0` => `1.15.0`
* `just-sysprocess` `0.6.0` => `0.8.0`
* Add task to run `npm audit fix` (#93)
* Upgrade `sbt-github-pages` to `0.7.0` (#96)

sbt-docusaur v0.7.0

---

website/docusaurus.config.js

Fixed: The doc site - the error caused by missing `additionalLanguages`

Fixed: The doc site - the error caused by missing additionalLanguages

---

changelogs/0.8.0.md

* Upgrade `sbt-github-pages` to `0.8.0` (#103)
* Upgrade `just-sysprocess` to `1.0.0` (#105)

sbt-docusaur v0.8.0

---

changelogs/0.8.1.md

* Upgrade `sbt-github-pages` to `0.8.1` (#110) to fix [Publish fails if the gh-pages branch does not already exist (#113)](/Kevin-Lee/sbt-github-pages/issues/113)

sbt-docusaur v0.8.1

---

project/plugins.sbt

Fix: sbt-ci-release had the wrong group ID for version 1.5.10

Fix: sbt-ci-release had the wrong group ID for version 1.5.10

---

changelogs/0.9.0.md
project/plugins.sbt

* Publish to `s01.oss.sonatype.org` (the new Maven central) (#120)
* Add `ALGOLIA_APP_ID` for Algolia (#141)

sbt-docusaur v0.9.0

---

build.sbt
src/main/scala/docusaur/Docusaur.scala
src/main/scala/docusaur/DocusaurPlugin.scala
src/main/scala/docusaur/npm/Npm.scala
src/main/scala/filef/FileF2.scala
website/package-lock.json
website/package.json

Close #151  - Upgrade libraries
* sbt-github-pages `0.8.1` => `0.9.0`
* cats `2.6.1` => `2.7.0`
* cats-effect `2.5.3` => `3.3.5`
* github4s `0.28.5` => `0.31.0`
* http4s `0.21.27` => `0.23.11`
* effectie `1.15.0` => `2.0.0-beta1`
* logger-f `1.15.0` => `2.0.0-beta1`
* hedgehog `0.7.0` => `0.8.0`
***
Add `extras-cats` `0.13.0`

Close #151  - Upgrade libraries

---

changelogs/0.10.0.md

* Upgrade libraries (#151)
* sbt-github-pages `0.8.1` => `0.9.0`
* cats `2.6.1` => `2.7.0`
* cats-effect `2.5.3` => `3.3.5`
* github4s `0.28.5` => `0.31.0`
* http4s `0.21.27` => `0.23.11`
* effectie `1.15.0` => `2.0.0-beta1`
* logger-f `1.15.0` => `2.0.0-beta1`
* hedgehog `0.7.0` => `0.8.0`
***
* Add `extras-cats` `0.13.0`

sbt-docusaur v0.10.0

---

build.sbt
project/plugins.sbt

Clsoe #155 - Upgrade libraries and sbt plugins
- cats-effect `3.3.5` => `3.3.12`
- extras `0.13.0` => `0.14.0`
- sbt-docusaur `0.9.0` => `0.10.0`
- sbt-devoops `2.16.0` => `2.20.0`

Clsoe #155 - Upgrade libraries and sbt plugins

---

changelogs/0.11.0.md

* Upgrade `sbt-github-pages` to `0.10.0` (#154)
* This version supports request timeout for publishing GitHub Pages
* Upgrade libraries and sbt plugins (#155)
* cats-effect `3.3.5` => `3.3.12`
* extras `0.13.0` => `0.14.0`
* sbt-docusaur `0.9.0` => `0.10.0`
* sbt-devoops `2.16.0` => `2.20.0`

sbt-docusaur v0.11.0

---

project/plugins.sbt

Upgrade: sbt plugins - `sbt-docusaur` `0.10.0` => `0.11.0` / `sbt-devoops` `2.20.0` => `2.22.0` / add `sbt-devoops-starter`

Upgrade: sbt plugins - sbt-docusaur 0.10.0 => 0.11.0 / sbt-devoops 2.20.0 => 2.22.0 / add sbt-devoops-starter

---

build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/docusaur/DocusaurPlugin.scala

Close #164 - Upgrade Scala, sbt, sbt-plugins and libraries
* sbt `1.6.2` => `1.7.2`
* Scala `2.12.12` => `2.12.17`
* sbt-github-pages `0.10.0` => `0.11.0`
* cats `2.7.0` => `2.8.0`
* cats-effect `3.3.12` => `3.3.14`
* github4s `0.31.0` => `0.31.2`
* http4s `0.23.11` => `0.23.16`
* http4s-blaze-client `0.23.11` => `0.23.12`
* effectie `2.0.0-beta1` => `2.0.0-beta2`
* logger-f `2.0.0-beta1` => `2.0.0-beta2`
* extras `0.14.0` => `0.20.0`
* Other sbt plugins

Close #164 - Upgrade Scala, sbt, sbt-plugins and libraries

---

changelogs/0.12.0.md

* Upgrade Scala, sbt, sbt-plugins and libraries (#164)
* sbt `1.6.2` => `1.7.2`
* Scala `2.12.12` => `2.12.17`
* sbt-github-pages `0.10.0` => `0.11.0`
* cats `2.7.0` => `2.8.0`
* cats-effect `3.3.12` => `3.3.14`
* github4s `0.31.0` => `0.31.2`
* http4s `0.23.11` => `0.23.16`
* http4s-blaze-client `0.23.11` => `0.23.12`
* effectie `2.0.0-beta1` => `2.0.0-beta2`
* logger-f `2.0.0-beta1` => `2.0.0-beta2`
* extras `0.14.0` => `0.20.0`
* Other sbt plugins

sbt-docusaur v0.12.0

---

build.sbt
src/main/scala/docusaur/Docusaur.scala
src/main/scala/docusaur/DocusaurKeys.scala
src/main/scala/docusaur/DocusaurPlugin.scala
src/main/scala/docusaur/npm/Npm.scala
src/main/scala/filef/FileError2.scala
src/main/scala/filef/FileF2.scala

Close #172 - Upgrade effectie and logger-f to 2.0.0-beta4, and sbt-github-pages to 0.12.0 / update the code accordingly / also upgrade other libraries
- effectie 2.0.0-beta2 => 2.0.0-beta4
- logger-f 2.0.0-beta2 => 2.0.0-beta4
- sbt-github-pages 0.11.0 => 0.12.0
- global sbt version 1.2.8 => 1.6.2
- hedgehog 0.9.0 => 0.10.1
- cats 2.8.0 => 2.9.0
- cats-effect 3.3.14 => 3.4.3
- http4s blaze client 0.23.12 => 0.23.13
- extras 0.20.0 => 0.26.0

Close #172 - Upgrade effectie and logger-f to 2.0.0-beta4, and sbt-github-pages to 0.12.0 / update the code accordingly / also upgrade other libraries

---

changelogs/0.13.0.md

* Upgrade `effectie` and `logger-f` to `2.0.0-beta4`, and `sbt-github-pages` to `0.12.0` (#172) - update the code accordingly / also upgrade other libraries
* effectie`2.0.0-beta2` => `2.0.0-beta4`
* logger-f`2.0.0-beta2` => `2.0.0-beta4`
* sbt-github-pages`0.11.0` => `0.12.0`
* global sbt version`1.2.8` => `1.6.2`
* hedgehog`0.9.0` => `0.10.1`
* cats`2.8.0` => `2.9.0`
* cats-effect`3.3.14` => `3.4.3`
* http4s blaze client`0.23.12` => `0.23.13`
* extras`0.20.0` => `0.26.0`

sbt-docusaur v0.13.0

---

changelogs/0.14.0.md

* Support multiple Google Analytics trackingIDs (multiple `GA_TRACKING_ID`s) (#186)

sbt-docusaur v0.14.0

---

build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/docusaur/Docusaur.scala
src/main/scala/docusaur/DocusaurPlugin.scala
src/main/scala/filef/FileError2.scala

Close #190 - Upgrade Scala, sbt, sbt plugins and libraries
* Scala to `2.12.18`
* sbt to `1.9.7`
* sbt-ci-release to `1.5.12`
* sbt-wartremover to `3.1.5`
* sbt-devoops to `3.0.0`
* sbt-github-pages to `0.13.0`
* cats to `2.10.0`
* cats-effect to `3.5.2`
* github4s to `0.32.1`
* circe to `0.14.6`
* http4s to `0.23.24`
* http4s-blaze-client to `0.23.15`
* effectie to `2.0.0-beta13`
* logger-f to `2.0.0-beta22`
* extras to `0.44.0`

Close #190 - Upgrade Scala, sbt, sbt plugins and libraries

---

changelogs/0.15.0.md

* Upgrade Scala, sbt, sbt plugins and libraries (#190)
* Scala to `2.12.18`
* sbt to `1.9.7`
* sbt-ci-release to `1.5.12`
* sbt-wartremover to `3.1.5`
* sbt-devoops to `3.0.0`
* sbt-github-pages to `0.13.0`
* cats to `2.10.0`
* cats-effect to `3.5.2`
* github4s to `0.32.1`
* circe to `0.14.6`
* http4s to `0.23.24`
* http4s-blaze-client to `0.23.15`
* effectie to `2.0.0-beta13`
* logger-f to `2.0.0-beta22`
* extras to `0.44.0`

sbt-docusaur v0.15.0

---

.github/workflows/build.yml
.github/workflows/release.yml
build.sbt

Close #203 - Bump libraries
- cats-effect to `3.5.3`
- http4s to `0.23.25`
- http4s-blaze-client to `0.23.16`
- effectie to `2.0.0-beta14`
- logger-f to `2.0.0-beta24`
- logback to `1.4.11`
- sbt-github-pages to `0.14.0`

Close #203 - Bump libraries

---

changelogs/0.16.0.md

* Bump libraries (#203)
* cats-effect to `3.5.3`
* http4s to `0.23.25`
* http4s-blaze-client to `0.23.16`
* effectie to `2.0.0-beta14`
* logger-f to `2.0.0-beta24`
* logback to `1.4.11`
* sbt-github-pages to `0.14.0`

sbt-docusaur v0.16.0

---

build.sbt
project/plugins.sbt

- Updated `sbt-github-pages` to 0.15.0
- Updated `cats-core` to 2.13.0
- Updated `cats-effect` to 3.5.7
- Updated `http4s` to 0.23.30
- Updated `http4s-blaze-client` to 0.23.17
- Updated `github4s` to 0.33.3
- Updated `effectie` to 2.0.0
- Updated `logger-f` to 2.1.18
- Updated `logback-classic` to 1.5.18
- Updated `hedgehog` to 0.12.0
- Updated `circe` to 0.14.12
- Updated `sbt-devoops` plugins to 3.2.0

Close #216 - Bump libraries and sbt plugins

---

changelogs/0.17.0.md

* Bump libraries and sbt plugins (#216)
- Updated `sbt-github-pages` to `0.15.0`
- Updated `cats-core` to `2.13.0`
- Updated `cats-effect` to `3.5.7`
- Updated `http4s` to `0.23.30`
- Updated `http4s-blaze-client` to `0.23.17`
- Updated `github4s` to `0.33.3`
- Updated `effectie` to `2.0.0`
- Updated `logger-f` to `2.1.18`
- Updated `logback-classic` to `1.5.18`
- Updated `hedgehog` to `0.12.0`
- Updated `circe` to `0.14.12`
- Updated `sbt-devoops` plugins to `3.2.0`

sbt-docusaur v0.17.0

---

website/docs/examples.md
website/docs/getting-started.md

Update docs: Bump sbt-docusaur to `v0.17.0` in examples and getting-started documentation

Update docs: Bump sbt-docusaur to `v0.17.0` in examples and getting-started documentation
